sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TESTS_ZEND_FORM_ANNOTATION_SUPPORT=true
    - TESTS_ZEND_FORM_RECAPTCHA_SUPPORT=true

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.5
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - HYDRATOR_VERSION="^1.1"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 5.6
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - HYDRATOR_VERSION="^1.1"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7
    - php: 7
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - HYDRATOR_VERSION="^1.1"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: hhvm 
    - php: hhvm 
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - HYDRATOR_VERSION="^1.1"
        - SERVICE_MANAGER_VERSION="^2.7.5"
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $EVENT_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:$EVENT_MANAGER_VERSION" ; fi
  - if [[ $EVENT_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:^3.0" ; fi
  - if [[ $HYDRATOR_VERSION != '' ]]; then composer require --no-update "zendframework/zend-stdlib:^2.7" ; fi
  - if [[ $HYDRATOR_VERSION != '' ]]; then composer require --no-update "zendframework/zend-hydrator:$HYDRATOR_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION = '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
