sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - LEGACY_DEPS="phpunit/phpunit"
    - TESTS_ZEND_FORM_ANNOTATION_SUPPORT=true
    - TESTS_ZEND_FORM_RECAPTCHA_SUPPORT=true
    - SITE_URL: https://zendframework.github.io/zend-form
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-form.git
    - secure: "nr4sIJy4elJkolkeNtNF4rqerQ32TcCD2i9j89o6xfVcO8140fJU9U9gkBhyq/XZc0H/tiIA/NnaKLp9wbeKRYO7qNi5VF+lUDhL2CJvOwlA1lTw48zLQ+CMHvjs5uo0wegCMaOh+L/EVlycRnoYc86gdCYjYlZMn/7B/ONEq+AM25vHEi1R/groSYVVnFCxGxoyVqRdWwgQOwfNM0GmwvAU7pukUj6Lw8ctFxErA2QflsupDg6YKv4907e0VmcvZzTAfOSVFjTFIt+wFDFR2cIf4dtps8MTqSJ5RQvqA3pe7fTRif+RtvsIe1JAz6tNUa4i5IKOk7E3G1vK4Hqwm2+mFH8p7dw4Xd0rK987ctLR/iV/lxxOMkQ3WRijalr/GwmF4m0aCsup2JeW+pf5L4pQclfxFTjm8xk1QqHH9sLidC/pq4tInOz3e8RPiE6JtgAvOA+omd0Upvuw2hdmyb6MkieCD6/1dlARLLZh5AKpb799wxo4qq6CRFcEXBP/8gXeepTO2dYd2ChjEYTinIHT19wWJhcYDLnCLqStND52/ZLp3FY7jQbBp/hblKm4N1+guf/Ic1bxHqpn8O5HBw3W05RJtHOIcURbHMnqcXhrrVmiV9yyS1RK7FFtu6tgyOKPIt0dY7g20dbT2cj6+zeoxaglbzCTxHUm9xcaA0Y="

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - CS_CHECK=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "G5waJvyj6YX8nI559QjMhSqNwZ0JTbF07x4UQM1Ej0AuoXpPvkd7s05zEdOV3VmM5gF78HIB7y3sHTcHptzTAc9eI/0O/5jpO/pAE9OWPXHewV+yENF1UgC7fuuyUAO9BXkXp+o+p3fjv+CMIvcY7f9GtUUgki8KxRP58MeXV4AFE1daicewY9fYYYPSQvw/C105TCEyz42xhfLUhyNqSFhGPKmQ90hYg4IW2pf5vzgl99d+mUBacF4gsvwI1GiaUF0lR0NQvn4bTSWxcJcB2KnjKRKtwZXfmkSCDA9dDTESK9CeoZlK70dzwk4g9npFiyD64vG7neH2Ux0XW3kNZzMnSFrqraTpgE6WCkK40D2zRZDe/ruhGGyU8t/SQmKwQy9bqUqMZ61iwosLCx5+Gr27gY/WRhepbSJNtABcvSaJKlPqTo6pYShfjCXPUuXqdkoNnb727o/JPIUFFJPcrR+XlGKj506KUC/vftXy/OPpJvoA6dZqBHrFkeb4WTiu3N3s/m5vW8NqeBU+08sZCWSSqFuhZb9R8+/DTemUJpzGMpi5qIx8+Jl5pl8BhKXZB4X/5KuYB7mSpbEsBuN/tm0Q5mCVFNFsKkFFlBOJy8sRnmy55a5enk7AytJqypCGKHUbpq8UI5VVzTLHsXQ7y9qMPE+5nkUpK1OIIN3hbPk="
    on_success: change
    on_failure: always
